variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

pages:
  image: python:3.8-buster
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
    - /^docs\/.*$/
